
apiVersion: automation.dcn.ssu.ac.kr/v1alpha1
kind: LogicalCluster
metadata:
  name: mec-cluster
  namespace: starlab
  tenant: starlab
  labels:
    automation.dcn.ssu.ac.kr/project: dcn
    automation.dcn.ssu.ac.kr/zone: private
spec:
  selector:
    matchLabels:
      automation.dcn.ssu.ac.kr/project: dcn
      automation.dcn.ssu.ac.kr/zone: private
  strategy:
    type: RollingUpdate
  clusters:
    - cluster:
      name: central-cluster
      metadata:
        labels:
          automation.dcn.ssu.ac.kr/location: kr-seoul
          automation.dcn.ssu.ac.kr/managed-by: emco-mec-central-mgmt
      spec:
        infrastructure:
          spec:
           provider: 
            name: openstack-v1
              profile: 
                name: openstack-medium-cluster-v1
                type: ClusterTemplate
                revision: 1.0.0
              override:
                kubernetesVersion: v1.25.0
            cni:
              name: cilium-v1
              blueprint:
                name: cilium-v1-default
                type: CNITemplate
                revision: 1.0.0
        software:
          - name: prometheus-v2.2
            blueprint: prometheus-default
            type: ApplicationTemplate
            revison: 1.0.0
    - cluster:
      name: seoul-edge-cluster
      metadata:
        labels:
          automation.dcn.ssu.ac.kr/location: kr-seoul
          automation.dcn.ssu.ac.kr/managed-by: emco-mec-central-mgmt
      spec:
        infrastructure:
          spec:
           provider: 
            name: openstack-v1
              blueprint: 
                name: openstack-small-cluster-v1
                type: ClusterTemplate
                revision: 1.0.0
              override:
                kubernetesVersion: v1.25.0
            cni:
              name: calico-v1
              blueprint: 
                name: calico-v1-default
                type: CNITemplate
                revision: 1.0.0
        software:
          - name: prometheus-v2.2
            blueprint: prometheus-default
            type: ApplicationTemplate
            revison: 1.0.0
    - cluster:
      name: busan-edge-cluster
      metadata:
        labels:
          automation.dcn.ssu.ac.kr/location: kr-busan
          automation.dcn.ssu.ac.kr/managed-by: emco-mec-central-mgmt
      spec:
        infrastructure:
          spec:
           provider: 
            name: openstack-v1
              blueprint: 
                name: openstack-small-cluster-v1
                type: ClusterTemplate
                revision: 1.0.0
              override:
                kubernetesVersion: v1.25.0
            cni:
              name: calico-v1
              blueprint: 
                name: calico-v1-default
                type: CNITemplate
                revision: 1.0.0
        software:
          - name: prometheus-v2.2
            blueprint: prometheus-default
            type: ApplicationTemplate
            revison: 1.0.0
    - cluster:
      name: gwangju-edge-cluster
      metadata:
        labels:
          automation.dcn.ssu.ac.kr/location: kr-gwangju
          automation.dcn.ssu.ac.kr/managed-by: emco-mec-central-mgmt
      spec:
        infrastructure:
          spec:
           provider: 
            name: openstack-v1
              blueprint: 
                name: openstack-small-cluster-v1
                type: ClusterTemplate
                revision: 1.0.0
              override:
                kubernetesVersion: v1.25.0
            cni:
              name: calico-v1
              blueprint: 
                name: calico-v1-default
                type: CNITemplate
                revision: 1.0.0
        software:
          - name: prometheus-v2.2
            blueprint: prometheus-default
            type: ApplicationTemplate
            revison: 1.0.0